name: Collect Telegram Configs

on:
  schedule:
    - cron: '0 */8 * * *'  # Ù‡Ø± Û¸ Ø³Ø§Ø¹Øª
  workflow_dispatch:       # Ø§Ø¬Ø±Ø§ÛŒ Ø¯Ø³ØªÛŒ

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run collector script
        env:
          API_ID: ${{ secrets.API_ID }}
          API_HASH: ${{ secrets.API_HASH }}
          PYROGRAM_SESSION_B64: ${{ secrets.PYROGRAM_SESSION_B64 }}
        run: python collect_configs.py

      - name: Commit & Push output files
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions@users.noreply.github.com"
          git add output/ all_configs.txt last_index.txt
          git commit -m "ðŸ”„ Auto update configs and reset index [$(date -u)]" || echo "No changes"
          git push
